version: "3.9"
services:
  db:
    image: "mysql:8.0"
    container_name: jpa-study
    restart: always
    ports:
      - "3308:3306"
    volumes:
      - ./etc/db:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jpa
